-- 20240702 数据源连接表新增备份密码字段
alter table "JDDBMS"."DATA_SOURCE" add column("PASSWORD_COPY" VARCHAR2(128));
comment on column "JDDBMS"."DATA_SOURCE"."PASSWORD_COPY" is '密码备份';
-- 20240603 用户连接数据源历史信息表
CREATE TABLE "JDDBMS"."HISTORY_USER_LOG"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "GMT_CREATE" DATETIME(6),
    "GMT_MODIFIED" DATETIME(6),
    "USER_ID" INTEGER NOT NULL,
    "STATUS" TINYINT NOT NULL,
    "DATA_SOURCE_ID" INTEGER NOT NULL,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "JDDBMS"."HISTORY_USER_LOG" IS '历史用户登陆信息表';
COMMENT ON COLUMN "JDDBMS"."HISTORY_USER_LOG"."DATA_SOURCE_ID" IS '数据源ID';
COMMENT ON COLUMN "JDDBMS"."HISTORY_USER_LOG"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "JDDBMS"."HISTORY_USER_LOG"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "JDDBMS"."HISTORY_USER_LOG"."ID" IS '自增主键';
COMMENT ON COLUMN "JDDBMS"."HISTORY_USER_LOG"."STATUS" IS '登陆状态（1登陆，2离线）';
COMMENT ON COLUMN "JDDBMS"."HISTORY_USER_LOG"."USER_ID" IS '用户ID';

-- 20240703保存密码勾选字段
alter table "JDDBMS"."DATA_SOURCE" add column("IS_SAVE" BIT);
comment on column "JDDBMS"."DATA_SOURCE"."IS_SAVE" is '是否保存密码';

-- 20240701 归档表
CREATE TABLE "JDDBMS"."PIGENHOLE"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "USER_NAME" VARCHAR2(50),
    "FILTER" VARCHAR2(2000),
    "TABLES" VARCHAR2(2000),
    "UPDATE_TIME" DATE,
    "TASK_NAME" VARCHAR2(50)) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "JDDBMS"."PIGENHOLE" IS '归档表';
COMMENT ON COLUMN "JDDBMS"."PIGENHOLE"."FILTER" IS '过滤条件';
COMMENT ON COLUMN "JDDBMS"."PIGENHOLE"."ID" IS '主键ID';
COMMENT ON COLUMN "JDDBMS"."PIGENHOLE"."TABLES" IS '表名';
COMMENT ON COLUMN "JDDBMS"."PIGENHOLE"."TASK_NAME" IS '归档任务名称';
COMMENT ON COLUMN "JDDBMS"."PIGENHOLE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "JDDBMS"."PIGENHOLE"."USER_NAME" IS '用户';