-- TASK 表达梦兼容初始化脚本
-- 来源：jd-dbms-bisnuess/src/main/resources/db/migration/V2_1_9__task.sql
-- 注意：执行前请确认 JDDBMS schema 中不存在同名表，并做好数据库备份。

CREATE TABLE "JDDBMS"."TASK"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "GMT_CREATE" DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "GMT_MODIFIED" DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DATA_SOURCE_ID" BIGINT,
    "DATABASE_NAME" VARCHAR2(128),
    "SCHEMA_NAME" VARCHAR2(128),
    "TABLE_NAME" VARCHAR2(128),
    "DELETED" VARCHAR2(10),
    "USER_ID" BIGINT NOT NULL DEFAULT 0,
    "TASK_TYPE" VARCHAR2(128),
    "TASK_STATUS" VARCHAR2(128),
    "TASK_PROGRESS" VARCHAR2(128),
    "TASK_NAME" VARCHAR2(128),
    "CONTENT" BLOB,
    "DOWNLOAD_URL" VARCHAR2(512),
    NOT CLUSTER PRIMARY KEY("ID")
) STORAGE(ON "MAIN", CLUSTERBTR);

COMMENT ON TABLE "JDDBMS"."TASK" IS 'TASK TABLE';
COMMENT ON COLUMN "JDDBMS"."TASK"."ID" IS '主键';
COMMENT ON COLUMN "JDDBMS"."TASK"."GMT_CREATE" IS '创建时间';
COMMENT ON COLUMN "JDDBMS"."TASK"."GMT_MODIFIED" IS '修改时间';
COMMENT ON COLUMN "JDDBMS"."TASK"."DATA_SOURCE_ID" IS '数据源连接ID';
COMMENT ON COLUMN "JDDBMS"."TASK"."DATABASE_NAME" IS 'db名称';
COMMENT ON COLUMN "JDDBMS"."TASK"."SCHEMA_NAME" IS 'schema名称';
COMMENT ON COLUMN "JDDBMS"."TASK"."TABLE_NAME" IS 'table_name';
COMMENT ON COLUMN "JDDBMS"."TASK"."DELETED" IS '是否被删除，y表示删除，n表示未删除';
COMMENT ON COLUMN "JDDBMS"."TASK"."USER_ID" IS '用户id';
COMMENT ON COLUMN "JDDBMS"."TASK"."TASK_TYPE" IS '任务类型';
COMMENT ON COLUMN "JDDBMS"."TASK"."TASK_STATUS" IS '任务状态';
COMMENT ON COLUMN "JDDBMS"."TASK"."TASK_PROGRESS" IS '任务进度';
COMMENT ON COLUMN "JDDBMS"."TASK"."TASK_NAME" IS '任务名称';
COMMENT ON COLUMN "JDDBMS"."TASK"."CONTENT" IS '任务内容';
COMMENT ON COLUMN "JDDBMS"."TASK"."DOWNLOAD_URL" IS '下载地址';

CREATE INDEX "JDDBMS"."IDX_TASK_USER_ID" ON "JDDBMS"."TASK"("USER_ID");
